"use strict";document.addEventListener("DOMContentLoaded",function(){var _a;(_a=document.querySelector(".loading"))===null||_a===void 0?void 0:_a.classList.replace("hidden","flex");const toggleBtn=document.querySelector('[data-collapse-toggle="navbar-sticky"]')||null;const navMenu=document.getElementById("navbar-sticky")||null;toggleBtn.addEventListener("click",function(){navMenu.classList.toggle("hidden")});const isDarkMode=localStorage.getItem("darkMode")===null?!0:localStorage.getItem("darkMode")==="true";if(isDarkMode){document.body.classList.add("dark");updateIconColors(isDarkMode)}else{document.body.classList.remove("dark");updateIconColors(isDarkMode)}
const projects=[{title:"Ecommerce Web Application",description:"A full e-commerce web application coded with Angular, TypeScript and Bootstrab.",imgSrc:"assets/Screens/Ecommerce.webp",link:"https://mohamedkh122.github.io/EcommerceApp/"},{title:"Islamic Library",description:"An Islamic library includes Azkar, prayer time, a counter, and the Quran coded with Angular, TypeScript, and Tailwind.",imgSrc:"assets/Screens/Islamic.webp",link:"https://mohamedkh122.github.io/Azkar/"},{title:"TimeMaster Landing Page",description:"A landing page for TimeMaster Applicatoin coded with JS and Tailwind.",imgSrc:"assets/Screens/TimeMaster.webp",link:"https://mohamedkh122.github.io/landPageTimeMaster/"},{title:"Personal Portfolio",description:"A Portfolio coded with HTML5, CSS3, JS, and Bootstrab.",imgSrc:"assets/Screens/Portfolio.webp",link:"https://mohamedkh122.github.io/websiteBootstrab/"},{title:"Restaurant Landing Page",description:"A landing page for a restaurant, coded with high performance and SEO optimization.",imgSrc:"assets/Screens/LandPage.webp",link:"https://mohamedkh122.github.io/landingPageRestaurant/"},{title:"Book Mark (CRUD)",description:"A website helps in saving your favorite websites with the CRUD concept.",imgSrc:"assets/Screens/BookMark.webp",link:"https://mohamedkh122.github.io/bookmark/"},{title:"Weather web Application",description:"A weather web application coded with a real REST API.",imgSrc:"assets/Screens/Weather.webp",link:"https://mohamedkh122.github.io/weatherApp/"}];const projectCont=document.querySelector(".projectsCont");let output="";for(let i=0;i<projects.length;i++){output+=`<div class="px-3 basis-full md:basis-1/2 ">
  <div class="group relative p-2 h-full rounded-2xl border-2 border-gray-900 shadow-[inset_2px_2px_5px_0px_rgba(0,0,0,0.5),inset_-2px_-2px_6px_1px_rgba(130,0,219,0.5)] text-center">
  <img class="rounded-xl group-hover:blur-sm transition-all duration-500" src="${projects[i].imgSrc}" alt="${projects[i].title} Project" loading="lazy">
  <div class="hidingInfo rotate-y-180 group-hover:rotate-y-360 lg:px-5 transition-all duration-500 w-full h-full flex flex-col justify-center items-center rounded-2xl left-0 bg-[rgba(0,0,0,0.4)] z-10 text-center absolute top-0 opacity-0 group-hover:opacity-100">
  <a aria-label="${projects[i].title}" href="${projects[i].link}" class="text-gray-300">
<lord-icon
    src="https://cdn.lordicon.com/gsjfryhc.json"
    trigger="hover"
    colors="primary:#d1d5dc,secondary:#8930e8"
    style="width:100px;height:100px">
</lord-icon></a>
  <h3 class="text-title-text text-xl lg:text-2xl font-bold ">${projects[i].title}</h3>
  <p class="text-sm lg:text-base text-gray-300">${projects[i].description}</p>
  </div>
  </div>
  </div>`}
projectCont.innerHTML=output;setInterval(()=>{var _a;(_a=document.querySelector(".loading"))===null||_a===void 0?void 0:_a.classList.replace("h-[100svh]","h-0")},2000);setInterval(()=>{var _a;(_a=document.querySelector(".loading"))===null||_a===void 0?void 0:_a.remove()},2300)});function applyDarkMode(isDark){document.body.classList.toggle("dark",isDark);updateIconColors(isDark);localStorage.setItem("darkMode",isDark.toString())}
function updateIconColors(isDark){animatedIcons.forEach(icon=>{icon.setAttribute("colors",isDark?"primary:#f3f4f6,secondary:#8200db":"primary:#242424,secondary:#8200db")})}
const cursorDot=document.querySelector('.cursor-dot')||null;const cursorOutline=document.querySelector('.cursor-outline')||null;const animatedIcons=document.querySelectorAll('lord-icon');window.addEventListener('mousemove',(e)=>{const posX=e.clientX;const posY=e.clientY;cursorDot.style.left=`${posX}px`;cursorDot.style.top=`${posY}px`;cursorOutline.animate({left:`${posX}px`,top:`${posY}px`},{duration:500,fill:'forwards'})});document.addEventListener("scroll",()=>{const documentScrollVal=document.documentElement.scrollTop;const navbar=document.querySelector("nav")||null;if(documentScrollVal>150){navbar.classList.add("backdrop-blur-sm","shadow-[inset_0_1px_1px_0_rgb(255_254_249/0.3)]","bg-navbar")}else{navbar.classList.remove("backdrop-blur-sm","shadow-[inset_0_1px_1px_0_rgb(255_254_249/0.3)]","bg-navbar")}});const darkModeButton=document.querySelector("#darkButton")||null;if(darkModeButton){darkModeButton.addEventListener("click",()=>{const isDarkMode=localStorage.getItem("darkMode")==="true";applyDarkMode(!isDarkMode)})}
$(".owl-carousel").owlCarousel({slideSpeed:200,paginationSpeed:800,loop:!0,autoPlay:!0,autoplayTimeout:5,goToFirstSpeed:1000,navigation:!1,navigationText:["prev","next"],pagination:!1,responsive:!0,items:5,itemsDesktop:5,itemsDesktopSmall:5,itemsTablet:5,itemsMobile:5});const c=document.getElementById("c");const contactSection=document.getElementById("contact")||null;let ctx=c.getContext("2d");c.height=contactSection.offsetHeight;c.width=window.innerWidth;let matrix="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789@#$%^&*()*&^%+-/~{[|`]}";matrix=matrix.split("");let font_size=10;let columns=c.width/font_size;let drops=[];for(let x=0;x<columns;x++)
drops[x]=1;function draw(){document.body.classList.contains("dark")===!0?ctx.fillStyle="rgba(0, 0, 0, 0.04)":ctx.fillStyle="rgba(255, 255, 255, 0.04)";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#8300db83";ctx.font=font_size+"px arial";for(let i=0;i<drops.length;i++){let text=matrix[Math.floor(Math.random()*matrix.length)];ctx.fillText(text,i*font_size,drops[i]*font_size);if(drops[i]*font_size>c.height&&Math.random()>0.975)
drops[i]=0;drops[i]++}}
setInterval(draw,35);const userNameInput=document.querySelector("#userName");const userEmailInput=document.querySelector("#userEmail");const userMessageInput=document.querySelector("#userMessage");const submitButton=document.querySelector("#submitButton");submitButton.addEventListener("click",()=>{const arr=[userNameInput,userEmailInput,userMessageInput];const messagesWarn=document.querySelectorAll(".errorWarn");if(userNameInput.value&&userEmailInput.value&&userMessageInput.value){fetch("https://685563cb6a6ef0ed66325946.mockapi.io/api/portfolio/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:userNameInput.value,email:userEmailInput.value,message:userMessageInput.value})}).then((data)=>{arr.map((input,index)=>{input.value.length?messagesWarn[index].classList.replace("block","hidden"):!0});userNameInput.value="";userEmailInput.value="";userMessageInput.value="";toastr.options={"closeButton":!1,"debug":!1,"newestOnTop":!1,"progressBar":!1,"positionClass":"toast-top-right","preventDuplicates":!1,"onclick":null,"showDuration":"300","hideDuration":"1000","timeOut":"5000","extendedTimeOut":"1000","showEasing":"swing","hideEasing":"linear","showMethod":"fadeIn","hideMethod":"fadeOut"};toastr.success("Your Message Sent Succefully!")}).catch(err=>console.log(err))}else{arr.map((input,index)=>{!input.value.length?messagesWarn[index].classList.replace("hidden","block"):!0})}})